config/routes.rb
Rails.application.routes.draw do
  root 'workshops#index'

  get '/sign_in', to: 'users#new'
  post '/sign_in', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/favorites', to: 'favorites#index'

  resources :workshops, only: [:index, :show] do
    resource :favorites, only: [:create, :destroy]
  end

  namespace :admin do
    resources :workshops, except: :show
    resources :stations
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
# frozen_string_literal: true

# お気に入り
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :workshop
end

app/models/station.rb
# frozen_string_literal: true

# 駅
class Station < ApplicationRecord
  has_many :workshops
  validates :name, presence: true
end

app/models/user.rb
# frozen_string_literal: true

# ユーザー
class User < ApplicationRecord
  has_many :favorites
  has_many :workshops, through: :favorites
  has_secure_password validations: true
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/models/workshop.rb
# frozen_string_literal: true

# 施設
class Workshop < ApplicationRecord
  belongs_to :station
  has_many :favorites
  has_many :users, through: :favorites
  validates :name, presence: true
  validates :category, presence: true
  validates :address, presence: true
  validates :opening_time, presence: true
  validates :price, presence: true

  enum category: { coworking_space: 0, cafe: 1, other: 2 }
end

app/controllers/admin/stations_controller.rb
# frozen_string_literal: true

module Admin
  # 駅の登録・管理
  class StationsController < ApplicationController
    before_action :set_station, only: %i[show edit update destroy]
    def index
      @stations = Station.all
    end

    def new
      @station = Station.new
    end

    def create
      @station = Station.create(station_params)
      if @station.save
        redirect_to admin_stations_path
      else
        render 'new'
      end
    end

    def update
      if @station.update(station_params)
        redirect_to admin_stations_path
      else
        render 'edit'
      end
    end

    def destroy
      @station.destroy
      redirect_to admin_stations_path
    end

    private

    def station_params
      params.require(:station).permit(:name)
    end

    def set_station
      @station = Station.find(params[:id])
    end
  end
end

app/controllers/admin/workshops_controller.rb
# frozen_string_literal: true

module Admin
  # 施設登録・管理（管理者用）
  class WorkshopsController < ApplicationController
    def index
      @workshops = Workshop.page(params[:page]).per(20).order('updated_at DESC')
    end

    def new
      @workshop = Workshop.new
    end

    def create
      @workshop = Workshop.new(workshop_params)
      if @workshop.save
        redirect_to admin_workshops_path, notice: t('action.created', model: Workshop.model_name.human, name: @workshop.name)
      else
        render 'new'
      end
    end

    def edit
      @workshop = Workshop.find(params[:id])
    end

    def update
      @workshop = Workshop.find(params[:id])
      if @workshop.update(workshop_params)
        redirect_to admin_workshops_path, notice: t('action.updated', model: Workshop.model_name.human, name: @workshop.name)
      else
        render 'edit'
      end
    end

    def destroy
      @workshop = Workshop.find(params[:id])
      @workshop.destroy
      redirect_to admin_workshops_path, notice: t('action.destroyed', model: Workshop.model_name.human, name: @workshop.name)
    end

    private

    def workshop_params
      params.require(:workshop).permit(:name, :category, :address, :wifi,
                                       :seats_number, :opening_time, :price, :note, :station_id)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# ApplicationController
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  private

  def current_user
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/favorites_controller.rb
# frozen_string_literal: true

# お気に入り機能
class FavoritesController < ApplicationController
  def index
    @stations = Station.all
  end

  def create
    @favorite = Favorite.new(user_id: current_user.id, workshop_id: params[:workshop_id])
    if @favorite.save
      respond_to do |format|
        format.html { render partial: 'workshops/favorite', locals: { workshop: @favorite.workshop } }
      end
    else
      redirect_to root_path, notice: t('.error')
    end
  end

  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, workshop_id: params[:workshop_id])
    if @favorite.destroy
      respond_to do |format|
        format.html { render partial: 'workshops/favorite', locals: { workshop: @favorite.workshop } }
      end
    else
      redirect_to root_path, notice: t('.error')
    end
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# ログイン
class SessionsController < ApplicationController
  def create
    @user = User.find_by(email: session_params[:email])
    if @user&.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: t('.success')
    else
      flash.now[:danger] = t('.error')
      render 'new'
    end
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# ユーザー登録
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: t('sessions.create.success')
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/workshops_controller.rb
# frozen_string_literal: true

# 施設閲覧（ユーザー向け）
class WorkshopsController < ApplicationController
  def index
    @search_params = workshop_search_params
    @workshops = search(workshop_search_params)
    @stations = Station.all
  end

  def show
    @search_params = workshop_search_params
    @workshops = search(workshop_search_params)
    @stations = Station.all
    @workshop = Workshop.find(params[:id])
  end

  private

  def search(search_params)
    workshops = Workshop.all
    workshops_searched_by_station_id = search_by_station_id(workshops, search_params[:station_id])
    workshops_searched_by_category = search_by_category(workshops_searched_by_station_id, search_params[:category])
    search_by_wifi(workshops_searched_by_category, search_params[:wifi])
  end

  def search_by_station_id(workshops, station_id)
    station_id.present? ? workshops.where(station_id: station_id) : workshops
  end

  def search_by_category(workshops, category)
    category.present? ? workshops.where(category: category) : workshops
  end

  def search_by_wifi(workshops, wifi)
    wifi ? workshops.where(wifi: wifi) : workshops
  end

  def workshop_search_params
    params.fetch(:search, {}).permit(:station_id, :category, :wifi)
  end
end

app/views/admin/stations/_form.html.slim
= form_with model: [:admin, station] do |form|
  = form.text_field :name
  = form.submit

app/views/admin/stations/edit.html.slim
h3 #{@station.name}の駅名変更
= render 'form', station: @station

app/views/admin/stations/index.html.slim
.container
  div
    h1 駅管理ページ
  .my-3
    = link_to '新規登録', new_admin_station_path, class: 'h3'
  div
    h3.my-2 登録済み一覧
    - @stations.each do |station|
      div = link_to station.name, admin_station_path(station)

app/views/admin/stations/new.html.slim
h3 駅登録
- if @station.errors.any?
  p 登録できませんでした。
br
= render 'form', station: @station

app/views/admin/stations/show.html.slim
h1 = @station.name
= link_to '駅名変更', edit_admin_station_path
= link_to '駅削除', admin_station_path(@station), method: :delete

app/views/admin/workshops/_form.html.slim
= form_with model: [:admin, workshop], local: true do |form|

  - if workshop.errors.any?
    ul
      - workshop.errors.full_messages.each do |message|
        li
          = message

  table[border='1']
    tr
      th 項目
      th 登録内容
    tr
      td = Workshop.human_attribute_name(:name)
      td
        = form.text_field :name
    tr
      td = Workshop.human_attribute_name(:address)
      td
        = form.text_field :address
    tr
      td = Workshop.human_attribute_name(:station)
      td
        = form.collection_select(:station_id, Station.all,
        :id, :name, include_blank: true)
    tr
      td = Workshop.human_attribute_name(:category)
      td
        = form.select :category,
        Workshop.categories_i18n.invert, include_blank: true
    tr
      td = Workshop.human_attribute_name(:wifi)
      td
        = form.radio_button :wifi, true
        div あり
        = form.radio_button :wifi, false
        div なし
    tr
      td = Workshop.human_attribute_name(:seats_number)
      td
        = form.number_field :seats_number, min: 1
    tr
      td = Workshop.human_attribute_name(:opening_time)
      td
        = form.text_field :opening_time
    tr
      td = Workshop.human_attribute_name(:price)
      td
        = form.text_field :price
    tr
      td = Workshop.human_attribute_name(:note)
      td
        = form.text_area :note
  = form.submit

app/views/admin/workshops/edit.html.slim
h1 作業場所編集
= render 'form', workshop: @workshop

app/views/admin/workshops/index.html.slim
.pl-3
  .row
    h3 = notice

  .row
    h1 施設管理ページ

  .row.my-3
    = link_to '新規登録', new_admin_workshop_path, class: 'h3'

  .row.workshops_field
    h3.my-2 登録済み施設一覧
    div
      .py-3.border-bottom
        .row
          .col-2 編集・削除
          .col-2 更新日
        .row
          .col-1 = Workshop.human_attribute_name(:id)
          .col-1 = Workshop.human_attribute_name(:name)
          .col-1 = Workshop.human_attribute_name(:station)
          .col-1 = Workshop.human_attribute_name(:category)
          .col-1 = Workshop.human_attribute_name(:adress)
          .col-1 = Workshop.human_attribute_name(:wifi)
          .col-1 = Workshop.human_attribute_name(:seats_number)
          .col-1 = Workshop.human_attribute_name(:opening_time)
          .col-1 = Workshop.human_attribute_name(:price)
          .col-3 = Workshop.human_attribute_name(:note)
      - @workshops.each do |workshop|
        .py-3.border-bottom
          .row.mb-2
            .col-2
              .row.m-0
                = link_to '編集', edit_admin_workshop_path(workshop)
                div ・
                = link_to '削除', admin_workshop_path(workshop), method: :delete
            .col-2 = l(workshop.updated_at, format: :long)
          .row
            .col-1 = workshop.id
            .col-1 = workshop.name
            .col-1 = workshop.station.name
            .col-1 = workshop.category_i18n
            .col-1 = workshop.address
            .col-1 = workshop.wifi ? 'あり' : 'なし'
            .col-1 = workshop.seats_number.presence || '不明'
            .col-1 = workshop.opening_time
            .col-1 = workshop.price
            .col-3 = workshop.note.presence || '登録なし'

  = paginate @workshops

app/views/admin/workshops/new.html.slim
h1 作業場所作成
= render 'form', workshop: @workshop

app/views/favorites/index.html.slim
= render 'workshops/navbar'
.container
  = render 'workshops/title', stations: @stations
  .row.mt-5
    .col-3.px-3
      h5 #{current_user.name} さんの
      h5 お気に入りページ
    .col-9.px-5
      - if current_user.workshops.present?
        - current_user.workshops.each do |workshop|
          .card.mb-3.shadow-sm.bg-whitesmoke
            .card-body
              h4.card-title = workshop.name
              h6.card-subtitle.mb-2.text-muted = workshop.station.name
              p.card-text.mb-0 = workshop.address
              = link_to '詳細ページ', workshop, class: 'btn btn-primary float-right'
      - else
        p お気に入りは登録されていません

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content='text/html; charset=UTF-8' http-equiv='Content-Type' /
    link[rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"]
    title Shigotoba
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application',
      media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield
    script[src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"]

app/views/users/new.html.slim
= form_with model: @user, url: sign_in_path, local: true do |form|

  - if @user.errors.any?
    - @user.errors.full_messages.each do |message|
      .alert.alert-warning.m-0 = message

  .container.mt-5.p-5
    .px-5
      h1 ユーザー新規登録
      .form-group
        = form.label :name, User.human_attribute_name(:name)
        = form.text_field :name, class: 'form-control'
      .form-group
        = form.label :email, User.human_attribute_name(:email)
        = form.text_field :email, class: 'form-control'
      .form-group
        = form.label :password, User.human_attribute_name(:password)
        = form.text_field :password, class: 'form-control'
      .form-group
        = form.label :password_confirmation, User.human_attribute_name(:password_confirmation)
        = form.text_field :password_confirmation, class: 'form-control'
      div
        = form.submit value: '登録する', class: 'btn btn-danger float-right'

app/views/workshops/_favorite.html.slim
- if current_user.workshops.include?(workshop)
  = link_to '★お気に入り済み', workshop_favorites_path(workshop), method: :delete, class: 'favorite_destroy_button btn btn-warning float-right mr-2'
- else
  = link_to '★お気に入り', workshop_favorites_path(workshop), method: :post, class: 'favorite_create_button btn btn-outline-warning float-right mr-2'

app/views/workshops/_navbar.html.slim
- if logged_in?
  nav.navbar.bg-lightsteelblue.justify-content-end
    .mr-1
      = link_to 'お気に入り一覧', favorites_path, class: 'btn btn-warning'
- else
  nav.navbar.bg-lightsteelblue.justify-content-end
    .mr-1
      = link_to '新規登録', sign_in_path, class: 'btn btn-danger'
    .ml-1
      = link_to 'ログイン', login_path, class: 'btn btn-danger'
- if flash[:notice].present?
  .alert.alert-success.m-0 = flash[:notice]

app/views/workshops/_search_field.html.slim
.col-3.px-3
  = form_with scope: :search, url: workshops_path,
    method: :get, local: true do |form|
    h4 絞り込み条件
    .mt-5.mb-3
      = form.label :station_id, Workshop.human_attribute_name(:station)
      = form.collection_select(:station_id, Station.all, :id, :name,
        { selected: search_params[:station_id], include_blank: '選択しない' }, class: 'form-control')
    .mt-5.mb-5
      = form.label :category, Workshop.human_attribute_name(:category)
      = form.select :category, Workshop.categories_i18n.invert,
        { selected: search_params[:category], include_blank: '選択しない' }, class: 'form-control'
    h4 こだわり条件
    .mt-5.mb-5
      = form.label :wifi, "#{Workshop.human_attribute_name(:wifi)}あり", class: 'form-check-label mr-4'
      = form.check_box :wifi, { checked: search_params[:wifi] == 'true', class: 'form-check-input' },
        true, false
    .mt-5.mb-5
      = form.submit value: '検索する', class: 'btn btn-success float-right'

app/views/workshops/_title.html.slim
div
  .row
    = link_to 'SHIGOTOBA', root_path, class: 'h1 pt-3 text-reset text-decoration-none'
  .row
    .col-12
      .float-right
        p コワーキングスペース、カフェなどの作業場所を検索できます。<br>現在、下記の駅周辺の施設に対応しています。エリアは順次拡大予定です。
        div 対応中の駅（エリア）
        - stations.each do |station|
          span.mark.mr-2 = station.name

app/views/workshops/index.html.slim
= render 'navbar'
.container
  = render 'title', stations: @stations
  .row.mt-5
    = render 'search_field', search_params: @search_params
    .workshops-field.col-9.px-5
      - @workshops.each do |workshop|
        .card.mb-3.shadow-sm.bg-whitesmoke
          .card-body
            h4.card-title = workshop.name
            h6.card-subtitle.mb-2.text-muted = workshop.station.name
            p.card-text.mb-0 = workshop.address
            = link_to '詳細ページ', workshop, class: 'btn btn-primary float-right'
            - if logged_in?
              .favorite_button_field = render 'favorite', workshop: workshop

app/views/workshops/show.html.slim
= render 'navbar'
.container
  = render 'title', stations: @stations
  .row.mt-5
    = render 'search_field', search_params: @search_params
    .workshop-field.col-9.px-5
      .card.shadow.bg-whitesmoke
        .card-body
          .row.justify-content-between
            h2.card-title.mb-4.ml-3 = @workshop.name
            - if logged_in?
              .favorite_button_field = render 'favorite', workshop: @workshop
          h4.card-subtitle.text-muted.mb-3 = @workshop.station.name
          p.card-text = @workshop.address
          table.table.table-bordered.my-5
            tbody
              tr
                th[style='width:20%'] = Workshop.human_attribute_name(:category)
                td[style='width:80%'] = @workshop.category_i18n
              tr
                th[style='width:20%'] #{Workshop.human_attribute_name(:wifi)}環境
                td[style='width:80%'] = @workshop.wifi ? 'あり' : 'なし'
              tr
                th[style='width:20%'] = Workshop.human_attribute_name(:seats_number)
                td[style='width:80%'] = @workshop.seats_number.presence || '不明'
              tr
                th[style='width:20%'] = Workshop.human_attribute_name(:opening_time)
                td[style='width:80%'] = @workshop.opening_time
              tr
                th[style='width:20%'] = Workshop.human_attribute_name(:price)
                td[style='width:80%'] = @workshop.price
          p.card-text.my-5 = simple_format(@workshop.note)